#!/bin/bash
ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
JAVA_OPTS="-javaagent:$ROOT/build/distributions/hello-world-service/lib/aspectjweaver-1.8.10.jar $JAVA_OPTS"
$ROOT/build/distributions/hello-world-service/bin/hello-world-service "$@"
