// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.lmlt.actor.example.message



@SerialVersionUID(0L)
final case class HelloEvt(
    num: Long = 0L
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[HelloEvt] with com.trueaccord.lenses.Updatable[HelloEvt] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      if (num != 0L) { __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(1, num) }
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
      {
        val __v = num
        if (__v != 0L) {
          _output__.writeInt64(1, __v)
        }
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.lmlt.actor.example.message.HelloEvt = {
      var __num = this.num
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 8 =>
            __num = _input__.readInt64()
          case tag => _input__.skipField(tag)
        }
      }
      com.lmlt.actor.example.message.HelloEvt(
          num = __num
      )
    }
    def withNum(__v: Long): HelloEvt = copy(num = __v)
    def getFieldByNumber(__fieldNumber: Int): scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = num
          if (__t != 0L) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PLong(num)
      }
    }
    override def toString: String = _root_.com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.lmlt.actor.example.message.HelloEvt
}

object HelloEvt extends com.trueaccord.scalapb.GeneratedMessageCompanion[com.lmlt.actor.example.message.HelloEvt] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[com.lmlt.actor.example.message.HelloEvt] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.lmlt.actor.example.message.HelloEvt = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    com.lmlt.actor.example.message.HelloEvt(
      __fieldsMap.getOrElse(__fields.get(0), 0L).asInstanceOf[Long]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.lmlt.actor.example.message.HelloEvt] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      com.lmlt.actor.example.message.HelloEvt(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[Long]).getOrElse(0L)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = MessageProto.javaDescriptor.getMessageTypes.get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = MessageProto.scalaDescriptor.messages(2)
  def messageCompanionForFieldNumber(__fieldNumber: Int): _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__fieldNumber)
  def enumCompanionForFieldNumber(__fieldNumber: Int): _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = com.lmlt.actor.example.message.HelloEvt(
  )
  implicit class HelloEvtLens[UpperPB](_l: _root_.com.trueaccord.lenses.Lens[UpperPB, com.lmlt.actor.example.message.HelloEvt]) extends _root_.com.trueaccord.lenses.ObjectLens[UpperPB, com.lmlt.actor.example.message.HelloEvt](_l) {
    def num: _root_.com.trueaccord.lenses.Lens[UpperPB, Long] = field(_.num)((c_, f_) => c_.copy(num = f_))
  }
  final val NUM_FIELD_NUMBER = 1
}
